Eppo-exp/sdk-common-jdk

- .github/workflows/lint-test-sdk.yml
- .github/workflows/publish-sdk.yml
- .github/workflows/publish-snapshot.yml
- README.md
- build.gradle
This PR makes it so every push to `main` will publish a new SNAPSHOT version of the library to Sonatype. This will be the bleeding edge version.
Configured all secrets and verified that the workflow works as intended. Release showed up here https://s01.oss.sonatype.org/content/repositories/snapshots/cloud/eppo/sdk-common-jvm/1.0.0-SNAPSHOT/
> chore: Upload artifacts from Github CI

- .github/workflows/lint-test-sdk.yml
- .github/workflows/publish-sdk.yml
- .github/workflows/publish-snapshot.yml
- README.md
- build.gradle
Just some housekeeping. Set the version to v1.0.0 so that will be the first non-snapshot version of this artifact. Then we can update both SDKs to use that instead of the snapshot version
> chore: Prepare for next release iteration

- .github/workflows/lint-test-sdk.yml
- .github/workflows/publish-snapshot.yml
This makes sure that this library remains java 8 compatible, otherwise it can't be use from https://github.com/Eppo-exp/java-server-sdk
> chore: Build and publish artifacts with Java 8

- .github/workflows/publish-sdk.yml
- .github/workflows/publish-snapshot.yml
- README.md
- build.gradle
* Bump version to v2.0.0
* Update publish workflows to distinguish between snapshot and release
> chore: Prepare for v2.0.0 release

- .github/workflows/publish-sdk.yml
- build.gradle
Should fix https://github.com/Eppo-exp/sdk-common-jdk/actions/runs/9765392722/job/26955946224
> fix(ci): Add missing checkout fetch depth for spotless, version bump

- src/main/java/cloud/eppo/BaseEppoClient.java
- src/test/java/cloud/eppo/BaseEppoClientBanditTest.java
- src/test/java/cloud/eppo/BaseEppoClientTest.java
🎟️ **Ticket:** [FF-3012 - Rename shared EppoClient class so upstream SDKs can extend as EppoClient](https://linear.app/eppo/issue/FF-3012/rename-shared-eppoclient-class-so-upstream-sdks-can-extend-as)
To keep things simple for users of our SDKs, our plan is to have the Java and Android Eppo Client classes to continue to be EppoClient. To take advantage of this shared common repository, we want to rename the shared base client class for each SDK to extend.
> Rename base EppoClient class to BaseEppoClient

- .github/workflows/lint-test-sdk.yml
- build.gradle
Adding Java version 21 to the testing matrix to ensure the SDK operates as expected in newer version of Java
> Include Java version 21 in tests

- build.gradle
- src/main/java/cloud/eppo/BaseEppoClient.java
- src/main/java/cloud/eppo/ConfigurationRequestor.java
- src/main/java/cloud/eppo/ConfigurationStore.java
- src/main/java/cloud/eppo/EppoHttpClient.java
- src/main/java/cloud/eppo/IConfigurationStore.java
- src/main/java/cloud/eppo/api/Configuration.java
- src/test/java/cloud/eppo/BaseEppoClientBanditTest.java
- src/test/java/cloud/eppo/BaseEppoClientTest.java
- src/test/java/cloud/eppo/ConfigurationRequestorTest.java
- src/test/java/cloud/eppo/ProfileBaseEppoClientTest.java
- src/test/java/cloud/eppo/helpers/TestUtils.java
- src/test/resources/static/boolean-flag.json
- Android is migrating to use the common SDK and has some additional requirements around asynchronous fetching, asynchronous initial configuration and resolving race conditions from config sources (cache vs remote API).
- The race condition between a cache load and a remote fetch only happens during the initialization of the `BaseEppoClient`. Specifically, when the client is created with an initial configuration and then the async `loadConfiguration` method is called. In this case, we don't want the cache load to clobber the fetched configuration as the fetched flags are always the latest. On subsequent calls to load (or loadAsync), we already have a reference to a `Configuration` in memory, so a cache-load attempt is not needed.
- The `IConfigurationStore` interface from the javascript …
> feat: Async configuration handling using CompletableFutures and other config refactoring

- README.md
- build.gradle
- src/main/java/cloud/eppo/Utils.java
commons-codec is known to cause a plethora of issues on Android, as documented [in this blog post](https://blog.osom.info/2015/04/commons-codec-on-android.html).
Using `java.util.Base64` instead, allows us to work around that issue. This API has been introduced on Android SDK version 26.
> fix: Switch commons-codec Base64 to `java.util.Base64`

- build.gradle
- src/main/java/cloud/eppo/api/AbstractAssignmentCache.java
The `AbstractAssignmentCache` contains an implementation of the contract specificed in `IAssignmentCache` that the cache entry's value be used when determining the presence of a given cache entry. To allow specific cache implementations of `IAssignmentCache` to make use of this existing implementation, we need to either reimplement Map<String, String> to pass as a delegate, or extract a minimal interface for cache delegates.
-`CacheDelegate` interface for non map-based implementations
- retain the `protected AbstractAssignmentCache(final Map<String, String> delegate)` constructor and wrap the map in a `CacheDelegate` implementation.
> feat: extract minimal assignment cache map

- README.md
- build.gradle
- src/main/java/cloud/eppo/BaseEppoClient.java
- src/main/java/cloud/eppo/ConfigurationRequestor.java
- src/main/java/cloud/eppo/Constants.java
- src/test/java/cloud/eppo/BaseEppoClientBanditTest.java
- src/test/java/cloud/eppo/ConfigurationRequestorTest.java
towards FF-3558
Cross-SDK testing tools (scenario testing, benchmarking) require a consistent interface to building clients and one of the parameters passed is the `EPPO_BASE_URL`. Most, nearly all in fact, of the SDKs use a baseUrl of `https://fscdn.eppo.cloud/api` and endpoint constants of `/flag-config/v1/config` and `/flag-config/v1/bandits` for flag and bandit requests.
- use established constants in `Constants.java`
- Move `/api` to baseUrl for consistency.
> chore: use established constants for URL and endpoints

- README.md
- build.gradle
- src/main/java/cloud/eppo/BaseEppoClient.java
- src/test/java/cloud/eppo/BaseEppoClientTest.java
- src/test/java/cloud/eppo/helpers/TestUtils.java
🎟️ [linear](https://linear.app/eppo/issue/FF-3565/implement-graceful-mode-error-handling-in-initialization)
towards FF-3565
The SDK will throw an unchecked exception upon initialization/loading configuration if it is unable to fetch over the network; this can result in applications crashing. 
- log an error if an exception is thrown during configuration load, but only re-throw exceptions if `gracefulMode=false`
- unit tests simulating error at the HTTP level
- Unit test continuing to attempt assignment after failed fetch.
> fix: respect graceful mode during client initialization

- build.gradle
- src/main/java/cloud/eppo/Constants.java
- src/test/java/cloud/eppo/ConfigurationRequestorTest.java
- Expecting a major version bugfix, the baseUrl change was merged but without a major version bump
- move `api` back to the endpoints temporarily.
- cut release 3.5.4
- mark v3.5.3 as bad?
- plan for api in baseUrl change to coincide with next major bump.
> fix: rollback api in baseUrl fix temporarily

- .github/workflows/lint-test-sdk.yml
- Makefile
- src/test/java/cloud/eppo/BaseEppoClientTest.java
🎟️ Fixes FF-3560 towards FF-3085
👯‍♂️ **Related PRs**
- [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data/pull/83)
- [Update testing cloud function to accept branch name](https://github.com/Eppo-exp/eppo/pull/11418)
Changes are often made to the [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) repository to capture new behaviours, bugs and edge cases. When these changes are pushed to `main`, the SDKs are cloned locally (locally to the github action running) and their respective tests are run. These tests are set up and run by copies of the SDK test workflows - see [sdk-test-data workflow](https://github.com/Eppo-exp/sdk-test-data/blob/main/.github/workflows/test-sdks.yml). There are a number of limitations to this setup:
- Test steps are copied from the SDK’s respective …
> quality: parameterize sdk and test data branches

- build.gradle
- src/main/java/cloud/eppo/BaseEppoClient.java
- src/main/java/cloud/eppo/Constants.java
- src/main/java/cloud/eppo/FetchConfigurationTask.java
- src/test/java/cloud/eppo/BaseEppoClientTest.java
- src/test/java/cloud/eppo/helpers/TestUtils.java
_Eppo Internal_
🎟️ Towards [FF-3876](https://linear.app/eppo/issue/FF-3876/[android-sdk]-allow-polling-for-configuration)
The implementation for polling in the Java SDKs exists solely in the server SDK. A client has asked for the ability to poll within the Android SDK
Copy the polling implementation logic from the java server SDK's `EppoClient` up to the `BaseEppoClient`
- protected `startPolling` and `stopPolling` methods in the base client available to subclasses and tests.
> feat: polling in BaseEppoClient

- src/main/java/cloud/eppo/FetchConfigurationTask.java
- src/test/java/cloud/eppo/BaseEppoClientTest.java
fixes FF-3983
https://github.com/Eppo-exp/android-sdk/actions/runs/13246564228/job/36981211128
From this test failure (and successful re-reruns), it appears that it's relatively probable for a timer to be pre-empted by the system or otherwise cancelled in way that causes the SDK code to attempt to use a cancelled timer
Catch and log the illegal state
> fix: Catch timer exceptions

- src/main/java/cloud/eppo/BaseEppoClient.java
- src/main/java/cloud/eppo/api/Configuration.java
- src/test/java/cloud/eppo/BaseEppoClientTest.java
- src/test/java/cloud/eppo/api/ConfigurationBuilderTest.java
_Eppo Internal_
📜 [DD](https://www.notion.so/eppo/New-Java-SDK-methods-getConfiguration-and-getFlagType-19a49cc0114380709ff3e69f020650d8)
🎟️ Fixes FF-3454
GlossGenius (and, likely other clients) integrate with the Eppo SDK in such a way that the type a given flag is not known at the time the assignment is requested from the SDK. In v2 of the SDK (Java server), `getAssignmentVariation` was available, [but removed in v3 to favour typed assignment returns.](https://eppo-group.slack.com/archives/C05FKKPDTJR/p1730229809171679?thread_ts=1730226618.797779&cid=C05FKKPDTJR) This method returned both the resulting value and its type. This information was used to convert the resulting value to the appropriate type for further processing.
There is a precedence for similar methods in other SDKs:
- the …
> feat: `getConfig` and `getFlagType`

- src/main/java/cloud/eppo/BaseEppoClient.java
- src/main/java/cloud/eppo/ConfigurationRequestor.java
- src/main/java/cloud/eppo/callback/CallbackManager.java
- src/test/java/cloud/eppo/ConfigurationRequestorTest.java
- src/test/java/cloud/eppo/callback/CallbackManagerTest.java
Fixes FF-4107
[Notion Doc](https://www.notion.so/eppo/onConfigurationChanged-method-1af49cc0114380c6bd97f4ea1f780608?pvs=4)
Clients are looking for the ability to listen to changes to the confiugration
https://github.com/Eppo-exp/android-sdk/pull/159
- Callback manager to manage handles, cancelling and notifying callbacks
- centralized calls to `saveConfiguration` and included notifying callbacks
- new method on `EppoClient`: `onConfigurationChange`
> feat: onConfigurationChange

- .github/workflows/lint-test-sdk.yml
This allows the testing workflow to run on forked branches in friends' repositories
context: [#119](https://github.com/Eppo-exp/sdk-common-jdk/actions/runs/15122712648)
> fix: hardcode repo only for workflow_call runs of the workflow

- src/main/java/cloud/eppo/api/EppoValue.java
Allows one to switch over all possible `EppoValueType` cases with a compile-time failure if `EppoValueType` changes.
Simple `EppoValue.getType()` getter.
No documentation, consistent with other getters
No tests. Consistent with other getters
> Make EppoValue.type publicly accessible

- src/main/java/cloud/eppo/api/Configuration.java
- src/test/java/cloud/eppo/BaseEppoClientTest.java
- src/test/java/cloud/eppo/ConfigurationRequestorTest.java
This makes comparing flags between different `Configuration` versions easier. Otherwise, we must deserialize another `FlagConfigResponse` instance from `flagConfigJson`, which is slower.
Exposes the `flags.keySet()` to as public API on `Configuration`
No documentation because `Configuration.isEmpty()` has no documentation.
Added tests in the same places where `Configuration.isEmpty()` is tested.
> Add API to show all flag keys

- src/main/java/cloud/eppo/BanditEvaluationResult.java
- src/main/java/cloud/eppo/FlagEvaluationResult.java
- src/main/java/cloud/eppo/SDKKey.java
- src/main/java/cloud/eppo/api/BanditResult.java
- src/main/java/cloud/eppo/api/Configuration.java
- src/main/java/cloud/eppo/cache/AssignmentCacheEntry.java
- src/main/java/cloud/eppo/cache/AssignmentCacheKey.java
- src/main/java/cloud/eppo/model/ShardRange.java
- src/main/java/cloud/eppo/ufc/dto/Allocation.java
- src/main/java/cloud/eppo/ufc/dto/BanditCategoricalAttributeCoefficients.java
- src/main/java/cloud/eppo/ufc/dto/BanditCoefficients.java
- src/main/java/cloud/eppo/ufc/dto/BanditFlagVariation.java
- src/main/java/cloud/eppo/ufc/dto/BanditModelData.java
- src/main/java/cloud/eppo/ufc/dto/BanditNumericAttributeCoefficients.java
- src/main/java/cloud/eppo/ufc/dto/BanditParameters.java
- src/main/java/cloud/eppo/ufc/dto/BanditParametersResponse.java
- src/main/java/cloud/eppo/ufc/dto/BanditReference.java
- src/main/java/cloud/eppo/ufc/dto/FlagConfig.java
- src/main/java/cloud/eppo/ufc/dto/FlagConfigResponse.java
- src/main/java/cloud/eppo/ufc/dto/Shard.java
- src/main/java/cloud/eppo/ufc/dto/Split.java
- src/main/java/cloud/eppo/ufc/dto/TargetingCondition.java
- src/main/java/cloud/eppo/ufc/dto/TargetingRule.java
- src/main/java/cloud/eppo/ufc/dto/Variation.java
This makes unit testing easier for consumers. It shouldn't change any behaviors.
I generated everything with Android Studio. The only places I saw equals/hashCode/toString already had them directly after constructors, and ordered them: toString
equals
hashCode
so I preserved that position and order (and moved AssignmentCacheEntry's existing equals/hashCode to make it match that order).
No new documentation. This is just standard bean behavior
Your existing unit tests should suffice
> Added equals/hashCode/toString methods to all bean objects

- src/main/java/cloud/eppo/cache/AssignmentCacheEntry.java
See https://github.com/Eppo-exp/sdk-common-jdk/pull/127/files#r2141103699
Reverted to previous `AssignmentCacheEntry.equals()` implementation
None, same as before.
Unit tests?
> Reverted equals behavior change from PR 127

- .gitignore
Stops people from accidentally including `local.properties` in their PR if they develop in Android Studio
Creates a separate section in `.gitignore` for gradle files
> Ignore the local.properties gradle file Android Studio generates
